### ISSUE TITLE
Guide to approach remote opportunities 

### ISSUE THREAD

**Issue by HarshCasper** [developersIndia/wiki#16]
### Have you read the contributing guidelines for proposing a wiki?

- [X] I have read the contributing guidelines.

### What's this proposal about? What should this wiki cover? Who's the audience?

The wiki would detail about:

- How to approach remote opportunities in India? 
- How to prepare for interviews and land opportunities? 
- How to format resume and cover letter? 
- How to shortlist companies to apply to and put up a good application?

The audience includes folks with varied experience, ranging from college students to experienced professionals.  

### Choose the category for this wiki

Community Guide

### Are you interested in authoring this wiki guide?

Yes

### Code of Conduct

- [X] I agree to follow the community's Code of Conduct

**Comment by Bhupesh-V** [comment]
Hey, @HarshCasper thanks for submitting the proposal.
Do you think it will best suit in the FAQ category, since there are a bunch of questions around the same topic?
https://www.reddit.com/r/developersIndia/search/?q=remote%20job&restrict_sr=1&sr_nsfw=&include_over_18=1

> How to format resume and cover letter?

I think we can let this one go, maybe add a few tips, since we already have a resume wiki, we can link that one in this section.
Let me know if you have any clarifying questions, other than the stuff mentioned everything look good, we can go ahead with the proposal 👍🏽

**Comment by Bhupesh-V** [comment]
@HarshCasper did you get a chance to work on this?

**Comment by Bhupesh-V** [comment]
@HarshCasper Making this available for others, LMK if you can still work on it
